### ISSUE TITLE
inspect code fails when Symbol provided

### ISSUE THREAD

**Issue by rpearce** [evilsoft/crocks#296]
Example failure:
```js
const { Right } = require('crocks/Either')
Right(Symbol('42'))
```
gives the error
```
/path/to/node_modules/crocks/core/inspect.js:39
  return (" " + x)
              ^

TypeError: Cannot convert a Symbol value to a string
    at inspect (/path/to/node_modules/crocks/core/inspect.js:39:15)
    at /path/to/node_modules/crocks/Either/index.js:72:41
    at /path/to/node_modules/crocks/core/defineUnion.js:26:25
    at Object.caseOf (/path/to/node_modules/crocks/core/curry.js:25:12)
    at either (/path/to/node_modules/crocks/Either/index.js:81:20)
    at Either (/path/to/node_modules/crocks/Either/index.js:70:5)
    at /path/to/node_modules/crocks/core/compose.js:8:12
    at Object.<anonymous> (/path/to/index.js:5:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```
when I think it should return
```js
Right Symbol('42')
```

Here is what I believe a simple fix is, though it'd be pulled out to `ifSymbol(x)`:
```js
if (typeof x === "symbol") {
  return " " + x.toString()
}
```

**Comment by rpearce** [comment]
Going to put up a PR
